import { useState } from "react";
import AppShell from "../components/AppShell";
import { postJSON, useLiveState } from "../lib/api";
import Icon from "../components/Icon";
const prompts = ["Why is the Walled City worsening?", "Which zones are most affected?", "Which signals may be related?", "What may happen in the next hour?", "Are any data feeds degraded?"];
export default function Copilot() { const { state: s } = useLiveState(); const [q, setQ] = useState(""); const [messages, setMessages] = useState([]); const [loading, setLoading] = useState(false); async function ask(question) { const text = question.trim(); if (!text || loading)
    return; setMessages(m => [...m, { role: 'user', text }]); setQ(''); setLoading(true); try {
    const r = await postJSON('/api/copilot', { question: text });
    setMessages(m => [...m, { role: 'ai', text: r.answer, source: r.source, note: r.note }]);
}
catch (e) {
    setMessages(m => [...m, { role: 'ai', text: 'The Copilot endpoint is unavailable. Use the deterministic dashboard panels while the backend recovers.', source: 'system' }]);
}
finally {
    setLoading(false);
} } return <AppShell active="/copilot" title="AI Copilot"><main className="page"><div className="page-hero"><div><div className="eyebrow">GROUNDED CIVIC AI</div><h1>CityPulse Copilot</h1><p>Ask about the live city state. Answers are grounded in structured CityPulse facts; unsupported claims are rejected.</p></div><div className="grounded-badge"><Icon name="shield" size={14}/> Grounding enabled</div></div><div className="copilot-grid"><section className="panel chat-panel"><div className="chat-head"><div><div className="eyebrow">LIVE CONTEXT</div><b>{s ? `${s.city.score}/100 · ${s.anomalies.length} anomalies` : "Loading…"}</b></div><span className="source-pill">structured facts</span></div><div className="chat-body">{messages.length === 0 ? <div className="chat-empty"><div className="ai-orb"><Icon name="cpu" size={28}/></div><h3>Ask CityPulse what is happening.</h3><p>Examples below use the same live data shown across the dashboard.</p><div className="prompt-grid">{prompts.map(p => <button key={p} onClick={() => ask(p)}>{p}<Icon name="arrow" size={14}/></button>)}</div></div> : messages.map((m, i) => <div className={`chat-msg ${m.role}`} key={i}><div className="msg-avatar">{m.role === 'ai' ? <Icon name="cpu" size={15}/> : "You"}</div><div className="msg-bubble"><p>{m.text}</p>{m.note && <small>{m.source === 'llm' ? 'AI · grounded + validated' : m.note}</small>}</div></div>)}{loading && <div className="chat-msg ai"><div className="msg-avatar"><Icon name="cpu" size={15}/></div><div className="msg-bubble typing">Thinking from live facts…</div></div>}</div><div className="chat-input"><input value={q} onChange={e => setQ(e.target.value)} onKeyDown={e => { if (e.key === 'Enter')
    ask(q); }} placeholder="Ask about the city…"/><button className="button primary" onClick={() => ask(q)} disabled={loading}><Icon name="arrow" size={16}/></button></div></section><section className="panel"><div className="panel-head"><div><div className="eyebrow">TRUST LAYER</div><h2>How Copilot stays grounded</h2></div></div><div className="trust-list"><div><span>01</span><b>Structured context</b><p>Questions are answered from the current CityPulse facts/state.</p></div><div><span>02</span><b>Numbers checked</b><p>The validator rejects numbers not present in the supplied facts.</p></div><div><span>03</span><b>No causal claims</b><p>Possible links stay framed as associations, never proven causes.</p></div><div><span>04</span><b>Fallback</b><p>Without a Groq key or when validation fails, deterministic answers remain available.</p></div></div></section></div></main></AppShell>; }
