import { useEffect, useMemo, useState } from "react";
import AppShell from "../components/AppShell";
import StatusBadge from "../components/StatusBadge";
import TrendChart from "../components/TrendChart";
import ZoneDrawer from "../components/ZoneDrawer";
import { useLiveState, STATUS_COLOR, getJSON } from "../lib/api";

export default function Zones(){
 const {state:s}=useLiveState(); const [zones,setZones]=useState(null); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("all"); const [selected,setSelected]=useState(null); const [analytics,setAnalytics]=useState(null);
 useEffect(()=>{getJSON("/api/zones").then(setZones).catch(()=>{}); const load=()=>getJSON("/api/analytics?hours=6&interval_min=15").then(setAnalytics).catch(()=>{}); load(); const id=setInterval(load,30000); return ()=>clearInterval(id);},[]);
 const list=useMemo(()=>{if(!s)return[]; return s.zones.filter(z=>z.name.toLowerCase().includes(query.toLowerCase())).filter(z=>filter==="all"||z.status===filter).sort((a,b)=>a.score-b.score)},[s,query,filter]);
 return <AppShell active="/zones" title="Zone Explorer"><main className="page"><div className="page-hero"><div><div className="eyebrow">SPATIAL INTELLIGENCE</div><h1>Zone Explorer</h1><p>Compare pulse, trend, anomalies and next-hour direction across Jaipur.</p></div><div className="hero-actions"><span className="count-chip">{list.length} shown</span></div></div><div className="toolbar"><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search zones…"/><div className="filter-tabs">{["all","alert","watch","calm"].map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="zone-table panel"><div className="table-head"><span>Zone</span><span>Pulse</span><span>Status</span><span>Trend</span><span>Outlook</span></div>{list.map(z=>{const hist=(analytics?.points||[]).map(p=>p.zones[z.id]?.score).filter(v=>v!=null); const fc=s?.forecast?.find(f=>f.zone_id===z.id); return <button className="table-row" key={z.id} onClick={()=>setSelected(z.id)}><div className="table-zone"><div className="zone-avatar" style={{borderColor:STATUS_COLOR[z.status]}}>{z.name.slice(0,2).toUpperCase()}</div><div><b>{z.name}</b><span>{z.id} · {z.bpm} BPM</span></div></div><strong style={{color:STATUS_COLOR[z.status]}}>{z.score}</strong><StatusBadge status={z.status} compact/><div className="table-chart"><TrendChart points={hist.map(score=>({score}))} valueKey="score" height={60}/></div><div className={fc?.direction==='worse'?'trend-down':fc?.direction==='better'?'trend-up':'muted-label'}>{fc?`${fc.now} → ${fc.next_hour}`:"—"}</div></button>})}</div></main><ZoneDrawer zone={selected?zones?.zones.find(z=>z.id===selected):null} onClose={()=>setSelected(null)}/></AppShell>
}
